### ISSUE TITLE
Planned Features

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare-enhanced-shortcodes#6]
- [x] Individual network share count shortcode
- [ ] Floating buttons shortcode

**Comment by Nicholas-Cardot** [comment]
I'm not sure what you mean by a "floating button shortcode"

**Comment by DustinWStout** [comment]
So it would add the ability to add floating buttons via shortcode. (had a few people request this)

**Comment by Nicholas-Cardot** [comment]
Unfortunately that's not a practical shortcode. 

1. The floating buttons can't live inside the content area. They live in the footer.
2. There is an option in the Social Warfare Custom options on each post where you can turn them on for that particular post so this would be redundant anyways because the option to add them to a particular post already exists.
